import {
  Box,
  Button,
  Center,
  Container,
  FormControl,
  FormLabel,
  Heading,
  HStack,
  Input,
  Stack,
  useColorModeValue,
  VStack,
} from '@chakra-ui/react';
import { ethers } from 'ethers';
import { useContext, useRef, useState } from 'react';
import { toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Web3Storage } from 'web3.storage';
import { ContractAddressContext } from '../App';
import SidebarWithHeader from '../components/Layout';
import abi from '../utils/EvidenceContract.json';
toast.configure();

const defaultState = {
  TYPE: 'File',
  firid: '',
  // contentid: 'https://pbs.twimg.com/media/Emjs5JyXEAAm2yk?format=jpg&name=orig',
  contentid: 'Autogenerated',
  title: '',
};

const AddEvidence = () => {
  const contractAddress = useContext(ContractAddressContext);
  const [input, setInput] = useState(defaultState);
  const [chosenFiles, setChosenFiles] = useState([]);
  const [fileList, setFileList] = useState(null);
  const contractABI = abi.abi;
  const fileInputRef = useRef(null);

  const handleInputChange = e => {
    console.log(e);
    const { id, value } = e.target;
    setInput({ ...input, [id]: value });
  };

  const handleFileChange = async e => {
    console.log(e.target.files);
    let tmpArr = [];
    for (let file of e.target.files) {
      tmpArr.push(file.name);
    }
    let tmp = e.target.files;
    setFileList(tmp);
    setChosenFiles(tmpArr);
  };

  const addEvidence = async () => {
    try {
      if (!fileList) {
        toast.error('No file selected');
        return;
      }
      toast.info('⬆️ File upload initiated.', {
        position: 'top-right',
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
      });
      const token =
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweEI2NjMyQWYxRTdGRDY2MzQ0YTc1MUMyNUYxMWU0NzQ1QjM5ODAxNTciLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NTEwNTgxNjE1OTksIm5hbWUiOiJNaW5pIFByb2plY3QgQVBJIFRva2VuIn0.xNpnrMvkZYPnrTKpoidL3VEYIMQDIOOL9bqpEyTt9Lw';
      const client = new Web3Storage({ token });
      const cid = await client.put(fileList, {
        name: 'test',
        maxRetries: 3,
      });
      console.log('CID', cid);
      input.contentid = cid;
      console.log(input);
      toast('File upload completed.', {
        position: 'top-right',
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
      });
      const { ethereum } = window;
      const provider = new ethers.providers.Web3Provider(ethereum);
      const signer = provider.getSigner();
      const contract = new ethers.Contract(
        contractAddress,
        contractABI,
        signer
      );
      const txn = await contract.createEvidence(
        input.contentid,
        input.title,
        input.firid
      );
      toast.info('⛏️ Transaction Initiated.', {
        position: 'top-right',
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
      });
      await txn.wait();
      toast('📦 Evidence Added Successfully.', {
        position: 'top-right',
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
      });
      setFileList(null);
      setChosenFiles([]);
    } catch (err) {
      console.log('Error: ', err);
      toast.error(
        '⛏️ Transaction Failed. Something went wrong. Make sure FIR ID is correct and files are uploaded successfully.',
        {
          position: 'top-right',
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
        }
      );
    }
  };

  const submitHandler = e => {
    e.preventDefault();
    console.log(input);
    addEvidence();
    setInput(defaultState);
  };

  return (
    <SidebarWithHeader currActive={'/add-evidence'}>
      <VStack>
        <Heading>Add Evidence Page!</Heading>
        <Container maxW={'container.md'}>
          <Box
            rounded={'lg'}
            bg={useColorModeValue('white', 'gray.700')}
            boxShadow={'lg'}
            p={8}
            as="form"
            onSubmit={submitHandler}
          >
            <Stack spacing={4}>
              <HStack>
                <FormControl isRequired>
                  <FormLabel htmlFor="firid">FIR ID</FormLabel>
                  <Input
                    id="firid"
                    type="text"
                    value={input.firid}
                    onChange={handleInputChange}
                  />
                </FormControl>
                <FormControl isReadOnly>
                  <FormLabel htmlFor="contentid">Content ID</FormLabel>
                  <Input
                    id="contentid"
                    type="text"
                    value={input.contentid}
                    onChange={handleInputChange}
                  />
                </FormControl>
              </HStack>
              <FormControl isRequired>
                <FormLabel htmlFor="title">Title</FormLabel>
                <Input
                  id="title"
                  type="text"
                  value={input.title}
                  onChange={handleInputChange}
                />
              </FormControl>
              <FormControl>
                <FormLabel htmlFor="filechooser">Choose file</FormLabel>
                {/* create a button to choose a file from directory */}
                <Center>
                  <Input
                    id="filechooser"
                    type={'file'}
                    border="none"
                    multiple
                    value={input.filechooser}
                    onChange={handleFileChange}
                    display="none"
                    ref={fileInputRef}
                  ></Input>
                  <Button
                    onClick={ev => {
                      console.log('button clickeed');
                      fileInputRef.current.click();
                    }}
                  >
                    Choose file
                  </Button>
                </Center>
                <ol>
                  {chosenFiles.map((file, index) => (
                    <li key={index}>{file}</li>
                  ))}
                </ol>
              </FormControl>
              <Stack spacing={10} pt={2}>
                <Button
                  loadingText="Submitting"
                  size="lg"
                  bg={'cyan.400'}
                  color={'white'}
                  _hover={{
                    bg: 'cyan.500',
                  }}
                  type="submit"
                >
                  Add
                </Button>
              </Stack>
            </Stack>
          </Box>
        </Container>
      </VStack>
    </SidebarWithHeader>
  );
};
export default AddEvidence;
