import {
  Box,
  Button,
  Container,
  FormControl,
  FormLabel,
  Heading,
  HStack,
  Input,
  Stack,
  Textarea,
  useColorModeValue,
  VStack,
} from '@chakra-ui/react';
import { ethers } from 'ethers';
import { useContext, useState } from 'react';
import { toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { ContractAddressContext } from '../App';
import SidebarWithHeader from '../components/Layout';
import abi from '../utils/EvidenceContract.json';
toast.configure();

const defaultState = {
  firid: 'Autogenerated',
  stationid: '',
  title: '',
  description: '',
};

const CreateFIR = () => {
  const contractAddress = useContext(ContractAddressContext);
  const [input, setInput] = useState(defaultState);
  const contractABI = abi.abi;

  const handleInputChange = e => {
    console.log(e);
    const { id, value } = e.target;
    setInput({ ...input, [id]: value });
  };

  const createFIR = async () => {
    try {
      const { ethereum } = window;
      const provider = new ethers.providers.Web3Provider(ethereum);
      const signer = provider.getSigner();
      const contract = new ethers.Contract(
        contractAddress,
        contractABI,
        signer
      );
      const txn = await contract.createFir(
        input.title,
        input.description,
        Date.now(),
        input.stationid
      );
      toast.info('⛏️ Transaction Initiated.', {
        position: 'top-right',
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
      });
      await txn.wait();
      toast('📦 FIR Created Successfully.', {
        position: 'top-right',
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
      });
    } catch (err) {
      console.log('Error: ', err);
      toast.error('⛏️ Transaction Failed. Something went wrong.', {
        position: 'top-right',
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
      });
    }
  };

  const submitHandler = e => {
    e.preventDefault();
    console.log(input);
    createFIR();
    setInput(defaultState);
  };

  return (
    <SidebarWithHeader currActive={'/create-fir'}>
      <VStack>
        <Heading>Create FIR Page!</Heading>
        <Container maxW={'container.md'}>
          <Box
            rounded={'lg'}
            bg={useColorModeValue('white', 'gray.700')}
            boxShadow={'lg'}
            p={8}
            as="form"
            onSubmit={submitHandler}
          >
            <Stack spacing={4}>
              <HStack>
                <FormControl isReadOnly>
                  <FormLabel htmlFor="firid" color={'gray'}>
                    FIR ID
                  </FormLabel>
                  <Input
                    id="firid"
                    type="text"
                    color={'gray'}
                    value={input.firid}
                    onChange={handleInputChange}
                  />
                </FormControl>
                <FormControl isRequired>
                  <FormLabel htmlFor="stationid">Station ID</FormLabel>
                  <Input
                    id="stationid"
                    type="text"
                    value={input.stationid}
                    onChange={handleInputChange}
                  />
                </FormControl>
              </HStack>
              <FormControl isRequired>
                <FormLabel htmlFor="title">Title</FormLabel>
                <Input
                  id="title"
                  type="text"
                  value={input.title}
                  onChange={handleInputChange}
                />
              </FormControl>
              <FormControl isRequired>
                <FormLabel htmlFor="description">Description</FormLabel>
                <Textarea
                  id="description"
                  type="text"
                  value={input.description}
                  onChange={handleInputChange}
                />
              </FormControl>
              <Stack spacing={10} pt={2}>
                <Button
                  loadingText="Submitting"
                  size="lg"
                  bg={'cyan.400'}
                  color={'white'}
                  _hover={{
                    bg: 'cyan.500',
                  }}
                  type="submit"
                >
                  Create
                </Button>
              </Stack>
            </Stack>
          </Box>
        </Container>
      </VStack>
    </SidebarWithHeader>
  );
};
export default CreateFIR;
